Write programs in Python using NumPy library to do the following:

In [2]:
import numpy as np
import pandas as pd

a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis.


In [6]:
# Create a random 2D array of integers for demonstration
random_array = np.random.randint(1, 100, size=(4, 6))

# Calculate the mean along axis 1
mean_values = np.mean(random_array, axis=1)

# Calculate the standard deviation along axis 1
std_deviation = np.std(random_array, axis=1)

# Calculate the variance along axis 1
variance = np.var(random_array, axis=1)

print("Mean values along axis 1:")
print(mean_values)
print("Standard deviation along axis 1:")
print(std_deviation)
print("Variance along axis 1:")
print(variance)

Mean values along axis 1:
[66.33333333 59.5        50.16666667 46.        ]
Standard deviation along axis 1:
[17.35575473 32.64327394 16.89592324 18.98244803]
Variance along axis 1:
[ 301.22222222 1065.58333333  285.47222222  360.33333333]


b. Get the indices of the sorted elements of a given array.<br>
a. B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]


In [3]:
arr = np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])

indices_of_sorted_elements = np.argsort(arr)

print("Original array:", arr)
print("Indices of sorted elements:", indices_of_sorted_elements)

Original array: [56 48 22 41 78 91 24 46  8 33]
Indices of sorted elements: [8 2 6 9 3 7 1 0 4 5]


c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of the array and then reshape it into nx m array, n and m are user inputs given at the run time.

In [4]:
# Input the values of m and n from the user
m = int(input("Enter the number of rows (m): "))
n = int(input("Enter the number of columns (n): "))

# Create a 2-dimensional array of size m x n with random integer elements
original_array = np.random.randint(1, 100, size=(m, n))

# Print the original array's shape, type, and data type
print("Original Array:")
print("Shape:", original_array.shape)
print("Type:", type(original_array))
print("Data Type:", original_array.dtype)

# Reshape the array into an n x m array
reshaped_array = original_array.reshape(n, m)

# Print the reshaped array's shape, type, and data type
print("\nReshaped Array:")
print("Shape:", reshaped_array.shape)
print("Type:", type(reshaped_array))
print("Data Type:", reshaped_array.dtype)

# Display the original and reshaped arrays
print("\nOriginal Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

Enter the number of rows (m): 4
Enter the number of columns (n): 3
Original Array:
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data Type: int32

Reshaped Array:
Shape: (3, 4)
Type: <class 'numpy.ndarray'>
Data Type: int32

Original Array:
[[48 25 58]
 [85 40 10]
 [27 31 55]
 [24 11 91]]

Reshaped Array:
[[48 25 58 85]
 [40 10 27 31]
 [55 24 11 91]]


d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays.

In [5]:
# Create a sample array with some zeros, non-zeros, and NaN values
sample_array = np.array([0, 3, 0, 8, 2, np.nan, 0, 7, np.nan])

# Create arrays to store the indices of zero, non-zero, and NaN elements
zero_indices = np.where(sample_array == 0)[0]
nonzero_indices = np.where(sample_array != 0)[0]
nan_indices = np.where(np.isnan(sample_array))[0]

# Print the indices of zero, non-zero, and NaN elements
print("Indices of zero elements:", zero_indices)
print("Indices of non-zero elements:", nonzero_indices)
print("Indices of NaN elements:", nan_indices)

Indices of zero elements: [0 2 6]
Indices of non-zero elements: [1 3 4 5 7 8]
Indices of NaN elements: [5 8]
